mysite/blog/urls.py
# Мы объявили два шаблона, используя функцию path(). Первый шаблон не принимает
# никаких аргументов. Он сопоставляется с обработчиком post_list. Второй вызывает
# функцию post_detail и принимает в качестве параметров 4 элемента.

from django.urls import path
from . import views
from .feeds import LatestPostsFeed

# Мы определили пространство имен приложения в переменной app_name.
app_name = 'blog'

urlpatterns = [
    # закомментируйте шаблон для обработчика PostListView
    #  и раскомментируйте шаблон для post_list
    path('', views.post_list, name='post_list'),
    # Добавьте дополнительный URL-шаблон, чтобы была возможность обратиться к списку статей,
    # связанных с определенным тегом
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/mysite/urls.py
"""Новый шаблон, добавленный с помощью include, подключит конфигурацию
приложения блога. Все его адреса будут начинаться с blog/. Мы будем об-
ращаться к шаблонам приложения по пространству имен, например blog:post_list, blog:post_detail.
"""
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

#мы подключили необходимые модули и определили словарь карт сайта.
# Добавили шаблон URL’а, который соответствует адресу sitemap.xml и обработчику sitemap.
sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

mysite/blog/models.py
# Каждый атрибут представляет собой поле в базе данных. Django создает таблицу в базе данных для каждой
# модели, определенной в models.py.

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Собственный менеджер для получения всех опубликованных статей.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    # slug – это поле будет использоваться для формирования URL’ов.
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # author – это поле является внешним ключом и определяет отношение «один ко многим».
    # Мы также указали имя обратной связи от User к Post– параметр related_name. Так мы с легкостью
    # получим доступ к связанным объектам автора.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # поле отображает статус статьи. Мы использовали параметр CHOICES, для того чтобы ограничить
    # возможные значения из указанного выше списка STATUS_CHOICES.
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()  # Менеджер по умолчанию, Он возвращает все объекты из базы.
    published = PublishedManager()  # Наш новый менеджер.
    tags = TaggableManager()  # Позволит нам добавлять, получать список и удалять теги для объектов статей


    # Добавим функцию, обрабатыающую теги в виде списка строк.
    def _tags(self):
        return [t.name for t in self.tags.all()]


    # В Django метод модели get_absolute_url() должен возвращать канонический URL объекта.
    # Для реализации этого поведения мы будем использовать функцию reverse(),
    # которая дает возможность получать URL, указав имя шаблона и параметры.
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    # Класс Meta внутри модели содержит метаданные. Мы указали Django порядок сортировки статей по умолчанию
    #  – по убыванию даты публикации О том, что порядок убывающий, говорит префикс «-».
    class Meta:
        ordering = ('-publish',)

    # Метод _возвращает отображение объекта, понятное человеку.
    # Django использует его во многих случаях, например на сайте администрирования.
    def __str__(self):
        return self.title


# Модель содержит ForeignKey для привязки к определенной статье.
class Comment(models.Model):
    # Атрибут related_name позволяет получить доступ к комментариям конкретной статьи.
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # добавили булевое поле active, для того чтобы была возможность скрыть некоторые комментарии
    active = models.BooleanField(default=True)

    # определили поле created для сортировки комментариев в хронологическом порядке
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

mysite/blog/forms.py
#Это наша первая Django-форма.
from django import forms
from .models import Comment



class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
# Валидация поля также зависит от его типа. Например, поля email и to имеют
# тип EmailField. Оба могут получать только корректные e-mail-адреса
    email = forms.EmailField()
    to = forms.EmailField()
# Каждый тип по умолчанию имеет виджет для отображения
# в HTML. Виджет может быть изменен с помощью параметра widget.
    comments = forms.CharField(required=False, widget=forms.Textarea)


# Все, что нужно для создания формы из модели, – указать, какую модель использовать в опциях класса Meta.
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


# Пользователи будут использовать поле формы query для задания поискового запроса.
class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity
# Это функция агрегации Count из Django. Она позволяет выполнять агрегирующий запрос
#  для подсчета количества тегов на уровне базы данных.

# Django имеет встроенный класс для постраничного отображения - Paginator,, который позволит нам легко управлять им.
# Отредактируйте views.py, импортируйте классы-пагинаторы из Django и добавьте их в обработчик post_list:

# Принимаем необязательный аргумент tag_slug, который по умолчанию равен None.
# Этот параметр будет задаваться в URL’е.
def post_list(request, tag_slug=None):
    # В этой функции мы запрашиваем из базы данных все опубликованные статьи с помощью менеджера published.
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        # находим все опубликованные статьи и, если указан слаг тега,
        #  получаем соответствующий объект модели Tag
        tag = get_object_or_404(Tag, slug=tag_slug)
        # фильтруем изначальный список статей и оставляем только те, которые связаны с полученным тегом.
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # По 3 статьи на каждой странице.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)
        # Функция render() использует переданный контекст {'page': page, 'posts': posts} при формировании
        # шаблона 'blog/post/list.html', поэтому любая переменная контекста будет доступна в этом шаблоне.
        # Отредактируйте вызов функции render() в конце обработчика и передайте дополнительную переменную контекста.
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


# Это обработчик страницы статьи. Он принимает на вход аргументы year, month, day и post
# для получения статьи по указанным слагу и дате.
def post_detail(request, year, month, day, post):
    # Функция get_object_or_404 возвращает объект, который подходит по указанным параметрам
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    # Список активных комментариев к этой записи
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # Комментарий был опубликован
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создайте объект Comment, но пока не сохраняйте в базу данных
            new_comment = comment_form.save(commit=False)
            # Назначить текущий пост комментарию
            new_comment.post = post
            # Сохранить комментарий в базе данных
            new_comment.save()
    else:
        comment_form = CommentForm()
    # Формирование списка похожих статей
    # Получает все ID тегов текущей статьи. Метод QuerySet’а values_list() возвращает кортежи со значениями
    # заданного поля. Мы указали flat=True, чтобы получить список вида [1, 2, 3, ...];
    post_tags_ids = post.tags.values_list('id', flat=True)
    # Получает все статьи, содержащие хоть один тег из полученных ранее, исключая текущую статью;
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # Функция агрегации Count формирует поле same_tags, которое содержит количество совпадающих тегов;
    # Сортируем список опубликованных статей в убывающем порядке по количеству совпадающих тегов для отображения
    # первыми максимально похожих статей и делает срез результата для отображения только четырех статей
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    # Функцию render() используем для формирования HTML - шаблона. При этом передаём саму статью в виде словаря,
    # значения полей этого словаря будут доступны в шаблонах html по названию словаря post, например, чтобы получить
    # имя автора в шаблоне 'blog/post/detail.html' используем post.author.
    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'new_comment': new_comment,
        'similar_posts': similar_posts
    })


# Мы заменим наш post_list на класс-наследник ListView Django. Этот базовый
# класс обработчика списков позволяет отображать несколько объектов любого
# типа
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


# определяем функцию post_share, которая принимает объект запроса request и параметр post_id
def post_share(request, post_id):
    # Получение статьи по идентификатору.
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Форма была отправлена на сохранение.
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию.
            cd = form.cleaned_data
            # ... Отправка электронной почты.
# Нам нужно добавить в сообщение абсолютную ссылку на статью, мы используем метод объекта запроса
#  request.build_absolute_uri() и передаем в него результат выполнения get_absolute_url() статьи.
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "' \
                      '{} "'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:' \
                      '{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


# В добавленном коде мы создаем объект формы SearchForm. Поисковый запрос будет отправляться методом GET,
# чтобы результирующий URL содержал в себе фразу поиска в параметре query.
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        # Инициируем объект формы с параметрами
        form = SearchForm(request.GET)
        # Проверяем корректность введенных данных
        if form.is_valid():
            query = form.cleaned_data['query']
            # мы создаем объект SearchQuery, фильтруем с его помощью результаты и используем SearchRank
            # для ранжирования статей.
            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # Формируем запрос на поиск статей с использованием объекта SearchVector
            results = Post.objects.annotate(similarity=TrigramSimilarity('title', query),)\
                .filter(similarity__gt=0.2).order_by('-similarity')
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

mysite/blog/templates/blog/post/detail.html
<!-- В данном шаблоне настраиваем отображение полного содержимого статьи.-->

{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
	<h1>{{ post.title }}</h1>
	<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
	{{ post.body|markdown }}
<!-- Ссылка для доступа к странице формы. Lля динамического формирования ссылок используется шаблонный
тег url. Мы задаем пространство имен blog и URL с названием post_share, добавляем ID статьи
 в качестве параметра и благодаря этому получаем абсолютный URL.-->
	<p>
		<a href="{% url 'blog:post_share' post.id %}">Поделиться статьей по электронке</a>
	</p>
    <!-- добавьте следующий фрагмент для отображения рекомендуемых статей перед списком комментариев-->

    <!--Список тегов на страницу статьи-->
    <h3 class="tags">
        Рекомендованные Вам статьи по тегам
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </h3>
    {# Similar_posts #}
    {% for similar_post in similar_posts %}
      <h3>
        <a href="{{ similar_post.get_absolute_url }}">
          {{ similar_post.title }}
        </a>
      </h3>
    {% endfor %}
<!--Мы используем ORM Django в шаблоне, выполняя comments.count(). Обратите внимание,
что для вызова функций в шаблонах не нужно указывать круглые скобки. Тег with позволяет
назначить переменной новое имя, которое можно использовать внутри блока до ближайшего тега endwith.-->
	{% with comments.count as total_comments %}
		<h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
	{% endwith %}
<!--Здесь используется тег for для итерации по комментариям. Каждый комментарий пронумерован
 с помощью переменной forloop.counter, }}, которая содержит номер текущей итерации цикла.-->
    {# Comments #}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
				<!--мы отображаем имя автора, дату создания и текст комментария-->
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Здесь нет комментариев</p>
    {% endfor %}
<!--если new_comment не существует, мы показываем поля формы создания комментария,
в противном случае отображаем сообщение о его успешном сохранении.-->
	{% if new_comment %}
        <h2>Ваш комментарий был добавлен</h2>
    {% else %}
        <h2>Написать новый комментарий</h2>
        <form action="." method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<!--Мы отображаем ненумерованный список статей, используя переменную
контекста latest_posts, которую получаем из тега-->
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
<!-- С помощью тега указываем, что list.html унаследован от базового шаблона blog/base.html. -->

{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
  <h1>My Blog</h1>
<!--Если пользователь первый раз заходит в блог, он увидит все статьи. Если он
отфильтрует их по тегу, то увидит сообщение об используемом теге и соответствующий список-->
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <!--Добавим теги для каждой статьи отредактируем класс tags-->
    <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
<!-- В теле статьи мы применяем два фильтра: truncatewords, обрезающий текст после указанного
 количества слов, и linebreaks, преобразующий вывод в HTML с переносами строки. -->
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
<!--  Так как страница Page передается в шаблон статей под именем posts, подключаем
шаблон постраничного отображения, указав, чему будет равен параметр page.
  {% include "pagination.html" with page=posts %} -->

<!-- Так как теперь мы используем функцию post_list в качестве обработчика,
добавьте постраничное отображение для статей posts: -->
  {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
<!--Так же как и в обработчике поиска, мы проверяем, была ли форма отправлена с параметром query.-->
  {% if query %}
<!--Показываем результат – количество найденных статей и фразу, по которой осуществлялся поиск.-->
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
<!--Перед отправкой формы отображаем ее и кнопку поиска.-->
  {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
<!--Это шаблон для отображения формы или информации об успешной отправке сообщения.-->
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
<!--Мы создали HTML-элемент формы, который будет отправляться на сервер методом POST
И добавили объект формы, дав Django указание сгенерировать ее поля как HTML-элементы параграфа <p>
 с помощью метода as_p.-->
    <form action="." method="post">
        <!--{{ form.as_p }} Если мы хотим выводить каждое поле по отдельности,
        можно итерировать по ним таким образом:-->
        {% for field in form %}
            <div>
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
<!--Тег csrf_token представляет собой скрытое поле с автоматически сгенерированным токеном для защиты
 от подделки межсайтовых запросов -->
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
    {% endif %}
{% endblock %}